package constants;

public class AotstmPayload {
	
	
	public String AotstmCreateRTR(String ticketNum) {

		return "<soapenv:Envelope soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:ch=\"http://cio.att.com/commonheader/v3\" xmlns:ns=\"http://aots.att.com/ticket/v1\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:tkt=\"http://tktsvc.aots.att.com/ticket\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n"
				+ "    <soapenv:Header>\r\n"
				+ "        <wsse:Security soapenv:mustUnderstand=\"1\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
				+ "            <wsse:UsernameToken>\r\n"
				+ "                <wsse:Username>Attnow</wsse:Username>\r\n"
				+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">attnow0121</wsse:Password>\r\n"
				+ "            </wsse:UsernameToken>\r\n"
				+ "        </wsse:Security>\r\n"
				+ "    </soapenv:Header>\r\n"
				+ "    <soapenv:Body>\r\n"
				+ "        <ns:createTicketRequest>\r\n"
				+ "            <ns:createControlInput>\r\n"
				+ "                <tkt:RetrieveAssetInfo>D</tkt:RetrieveAssetInfo>\r\n"
				+ "                <tkt:AssetLookupType>BVOIP_RTR</tkt:AssetLookupType>\r\n"
				+ "            </ns:createControlInput>\r\n"
				+ "            <ch:WSHeader>\r\n"
				+ "                <ch:WSContext>\r\n"
				+ "                    <ch:FromAppId>NOWIA</ch:FromAppId>\r\n"
				+ "                    <ch:SourceIPAddress>ATTNOW</ch:SourceIPAddress>\r\n"
				+ "                </ch:WSContext>\r\n"
				+ "            </ch:WSHeader>\r\n"
				+ "            <ns:createTicketInput>\r\n"
				+ "                <tkt:Log>&quot;&quot;</tkt:Log>\r\n"
				+ "                <tkt:UserID>ATTNOW</tkt:UserID>\r\n"
				+ "                <tkt:ReportPhone>8772888363</tkt:ReportPhone>\r\n"
				+ "                <tkt:TroubleReptDescText>Circuit Down</tkt:TroubleReptDescText>\r\n"
				+ "                <tkt:ManagingOrg>MO-BGTN</tkt:ManagingOrg>\r\n"
				+ "                <tkt:ReporterEmailAddr/>\r\n"
				+ "                <tkt:KeyItemAffected>LKMRFLMFFW01-NODE1</tkt:KeyItemAffected>\r\n"
				+ "                <tkt:InternalLog>&quot;&quot;</tkt:InternalLog>\r\n"
				+ "                <tkt:ReportedBy>BVoIP VDNA</tkt:ReportedBy>\r\n"
				+ "                <tkt:Severity>6 - Other</tkt:Severity>\r\n"
				+ "                <tkt:ClientHelpdesk>ATTNOW</tkt:ClientHelpdesk>\r\n"
				+ "                <tkt:TicketRole>Main</tkt:TicketRole>\r\n"
				+ "                <tkt:TicketSource>ATTNOW</tkt:TicketSource>\r\n"
				+ "                <tkt:ProblemAbstract>SD- Aots-tm Ebond 1/3</tkt:ProblemAbstract>\r\n"
				+ "                <tkt:WorkQueue/>\r\n"
				+ "                <tkt:TicketType>E-Bonding</tkt:TicketType>\r\n"
				+ "                <tkt:ReptRequestType>Fault</tkt:ReptRequestType>\r\n"
				+ "                <tkt:ClientTicketNum>IMTASK0026560</tkt:ClientTicketNum>\r\n"
				+ "                <tkt:FunctionalArea>GLOBAL_AM</tkt:FunctionalArea>\r\n"
				+ "            </ns:createTicketInput>\r\n"
				+ "            <ns:assetInput>\r\n"
				+ "                <tkt:EndUserEmail/>\r\n"
				+ "                <tkt:ActiveOrg>MO-BGTN-VOIP</tkt:ActiveOrg>\r\n"
				+ "                <tkt:EndUserName/>\r\n"
				+ "                <tkt:AssetType>Equipment</tkt:AssetType>\r\n"
				+ "                <tkt:LocationID>UNKNOWN</tkt:LocationID>\r\n"
				+ "                <tkt:BvoipIndicator>Yes</tkt:BvoipIndicator>\r\n"
				+ "                <tkt:EndUserPhone/>\r\n"
				+ "                <tkt:ReptSvcLineDescText>BVOIP</tkt:ReptSvcLineDescText>\r\n"
				+ "                <tkt:AssetID>LKMRFLMFFW01-NODE1</tkt:AssetID>\r\n"
				+ "            </ns:assetInput>\r\n"
				+ "        </ns:createTicketRequest>\r\n"
				+ "    </soapenv:Body>\r\n"
				+ "</soapenv:Envelope>";



	}

public String AotstmUpdateRTR(String ticketNum) {

	return "<soapenv:Envelope soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:ch=\"http://cio.att.com/commonheader/v3\" xmlns:ns=\"http://aots.att.com/ticket/v1\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:tkt=\"http://tktsvc.aots.att.com/ticket\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n"
			+ "    <soapenv:Header>\r\n"
			+ "        <wsse:Security soapenv:mustUnderstand=\"1\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
			+ "            <wsse:UsernameToken>\r\n"
			+ "                <wsse:Username>Attnow</wsse:Username>\r\n"
			+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">attnow0121</wsse:Password>\r\n"
			+ "            </wsse:UsernameToken>\r\n"
			+ "        </wsse:Security>\r\n"
			+ "    </soapenv:Header>\r\n"
			+ "    <soapenv:Body>\r\n"
			+ "        <ns:updateTicketRequest>\r\n"
			+ "            <ns:updateControlInput>\r\n"
			+ "                <tkt:TicketNum>"+ticketNum+"</tkt:TicketNum>\r\n"
			+ "                <tkt:LockForUpdate>false</tkt:LockForUpdate>\r\n"
			+ "            </ns:updateControlInput>\r\n"
			+ "            <ch:WSHeader>\r\n"
			+ "                <ch:WSContext>\r\n"
			+ "                    <ch:FromAppId>NOWIA</ch:FromAppId>\r\n"
			+ "                    <ch:SourceIPAddress>ATTNOW</ch:SourceIPAddress>\r\n"
			+ "                </ch:WSContext>\r\n"
			+ "            </ch:WSHeader>\r\n"
			+ "            <ns:updateTicketInput>\r\n"
			+ "                <tkt:Log/>\r\n"
			+ "                <tkt:UserID>ATTNOW</tkt:UserID>\r\n"
			+ "                <tkt:ClientHelpdesk>ATTNOW</tkt:ClientHelpdesk>\r\n"
			+ "                <tkt:ProblemAbstract>SD- Aots-tm Ebond 1/3</tkt:ProblemAbstract>\r\n"
			+ "                <tkt:TicketState>Active</tkt:TicketState>\r\n"
			+ "                <tkt:InternalLog>Add logs Sn-Aotstm</tkt:InternalLog>\r\n"
			+ "                <tkt:Severity>6 - Other</tkt:Severity>\r\n"
			+ "            </ns:updateTicketInput>\r\n"
			+ "        </ns:updateTicketRequest>\r\n"
			+ "    </soapenv:Body>\r\n"
			+ "</soapenv:Envelope>";

	}

public String AotstmGetRTR(String ticketNum) {

	return "<soapenv:Envelope xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\"> \r\n"
			+ "    <soapenv:Header> \r\n"
			+ "       <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\" soapenv:mustUnderstand=\"1\"> \r\n"
			+ "          <wsse:UsernameToken> \r\n"
			+ "             <wsse:Username>em</wsse:Username> \r\n"
			+ "             <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">em=123</wsse:Password> \r\n"
			+ "          </wsse:UsernameToken> \r\n"
			+ "       </wsse:Security> \r\n"
			+ "    </soapenv:Header> \r\n"
			+ "    <soapenv:Body> \r\n"
			+ "       <p620:getTicketRequest xmlns:p620=\"http://aots.att.com/ticket/v1\"> \r\n"
			+ "          <p882:WSHeader xmlns:p882=\"http://cio.att.com/commonheader/v3\"> \r\n"
			+ "             <p882:WSContext> \r\n"
			+ "                <p882:FromAppId>EM</p882:FromAppId> \r\n"
			+ "                <p882:SourceIPAddress>135.79.209.20</p882:SourceIPAddress> \r\n"
			+ "             </p882:WSContext> \r\n"
			+ "          </p882:WSHeader> \r\n"
			+ "          <p620:getTicketInput> \r\n"
			+ "          <p735:TicketNum xmlns:p735=\"http://tktsvc.aots.att.com/ticket\">"+ticketNum+"</p735:TicketNum> \r\n"
			+ "             <p735:FieldsList xmlns:p735=\"http://tktsvc.aots.att.com/ticket\"> \r\n"
			+ "                <p735:String xsi:type=\"p735:Character\">Severity</p735:String> \r\n"
			+ "                <p735:String xsi:type=\"p735:Character\">Log</p735:String> \r\n"
			+ "                <p735:String xsi:type=\"p735:Character\">InternalLog</p735:String> \r\n"
			+ "             </p735:FieldsList> \r\n"
			+ "             <p735:LogQualifier xmlns:p735=\"http://tktsvc.aots.att.com/ticket\">2</p735:LogQualifier> \r\n"
			+ "             <p735:LogSortOrder xmlns:p735=\"http://tktsvc.aots.att.com/ticket\">D</p735:LogSortOrder> \r\n"
			+ "             <p735:LogFilter xmlns:p735=\"http://tktsvc.aots.att.com/ticket\"> \r\n"
			+ "                 <p735:NumberOfRows xmlns:p735=\"http://tktsvc.aots.att.com/ticket\">100</p735:NumberOfRows> \r\n"
			+ "             </p735:LogFilter> \r\n"
			+ " \r\n"
			+ "          </p620:getTicketInput> \r\n"
			+ "       </p620:getTicketRequest> \r\n"
			+ "    </soapenv:Body> \r\n"
			+ " </soapenv:Envelope>";

	}

public String AotstmCloseRTR(String ticketNum) {

	return "<soapenv:Envelope soapenv:encodingStyle=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:ch=\"http://cio.att.com/commonheader/v3\" xmlns:ns=\"http://aots.att.com/ticket/v1\" xmlns:soapenc=\"http://schemas.xmlsoap.org/soap/encoding/\" xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:tkt=\"http://tktsvc.aots.att.com/ticket\" xmlns:xsd=\"http://www.w3.org/2001/XMLSchema\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\">\r\n"
			+ "    <soapenv:Header>\r\n"
			+ "        <wsse:Security soapenv:mustUnderstand=\"1\" xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
			+ "            <wsse:UsernameToken>\r\n"
			+ "                <wsse:Username>Attnow</wsse:Username>\r\n"
			+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">attnow0121</wsse:Password>\r\n"
			+ "            </wsse:UsernameToken>\r\n"
			+ "        </wsse:Security>\r\n"
			+ "    </soapenv:Header>\r\n"
			+ "    <soapenv:Body>\r\n"
			+ "        <ns:updateTicketRequest>\r\n"
			+ "            <ns:updateControlInput>\r\n"
			+ "                <tkt:TicketNum>"+ticketNum+"</tkt:TicketNum>\r\n"
			+ "                <tkt:LockForUpdate>false</tkt:LockForUpdate>\r\n"
			+ "            </ns:updateControlInput>\r\n"
			+ "            <ch:WSHeader>\r\n"
			+ "                <ch:WSContext>\r\n"
			+ "                    <ch:FromAppId>NOWIA</ch:FromAppId>\r\n"
			+ "                    <ch:SourceIPAddress>ATTNOW</ch:SourceIPAddress>\r\n"
			+ "                </ch:WSContext>\r\n"
			+ "            </ch:WSHeader>\r\n"
			+ "            <ns:updateTicketInput>\r\n"
			+ "                <tkt:Log/>\r\n"
			+ "                <tkt:UserID>ATTNOW</tkt:UserID>\r\n"
			+ "                <tkt:ClientHelpdesk>ATTNOW</tkt:ClientHelpdesk>\r\n"
			+ "                <tkt:ProblemAbstract>SD- Aots-tm Ebond 1422</tkt:ProblemAbstract>\r\n"
			+ "                <tkt:TicketState>Cleared</tkt:TicketState>\r\n"
			+ "                <tkt:InternalLog>Closing Task</tkt:InternalLog>\r\n"
			+ "                <tkt:Severity>6 - Other</tkt:Severity>\r\n"
			+ "            </ns:updateTicketInput>\r\n"
			+ "        </ns:updateTicketRequest>\r\n"
			+ "    </soapenv:Body>\r\n"
			+ "</soapenv:Envelope>";

	}

}
