package constants;

public class RequestPayLoad {
	
	
	public String updateRequestBody(String ticketNum) {
		
		return "<?xml version='1.0' encoding='utf-8'?>\r\n"
				+ "<soap-env:Envelope xmlns:soap-env=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "    <soap-env:Header>\r\n"
				+ "        <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
				+ "            <wsse:UsernameToken>\r\n"
				+ "                <wsse:Username>expresst</wsse:Username>\r\n"
				+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">etkt0813</wsse:Password>\r\n"
				+ "            </wsse:UsernameToken>\r\n"
				+ "        </wsse:Security>\r\n"
				+ "    </soap-env:Header>\r\n"
				+ "    <soap-env:Body>\r\n"
				+ "        <ns0:updateTicketRequest xmlns:ns0=\"http://aots.att.com/ticket/v1\">\r\n"
				+ "            <ns1:WSHeader xmlns:ns1=\"http://cio.att.com/commonheader/v3\">\r\n"
				+ "                <ns1:WSContext>\r\n"
				+ "                    <ns1:FromAppId>ETT_aotsUpdateLog</ns1:FromAppId>\r\n"
				+ "                    <ns1:SourceIPAddress>express-ticketing-84d5594bc7-wvckz</ns1:SourceIPAddress>\r\n"
				+ "                </ns1:WSContext>\r\n"
				+ "            </ns1:WSHeader>\r\n"
				+ "            <ns0:updateTicketInput>\r\n"
				+ "                <ns2:Log xmlns:ns2=\"http://tktsvc.aots.att.com/ticket\">====================\r\n"
				+ "= Customer Comment =\r\n"
				+ "====================\r\n"
				+ "\r\n"
				+ "REPORTED BY: \r\n"
				+ " Mohit Chawla 3149717000 mc9844@att.com\r\n"
				+ "\r\n"
				+ "EXPRESS TICKETING CUSTOMER STATES: \r\n"
				+ "\r\n"
				+ "REPORT DETAIL: Ticket only, Do not cancel, close ticket\r\n"
				+ "\r\n"
				+ "REPORT DESCRIPTION: Test ticket\r\n"
				+ "\r\n"
				+ "==========================================\r\n"
				+ "======   Test/Dispatch/LCON Template =====\r\n"
				+ "==========================================\r\n"
				+ "TESTING AUTH: Yes\r\n"
				+ "DISPATCH AUTH: No\r\n"
				+ "CPE POWER: Y \r\n"
				+ "\r\n"
				+ "PRIMARY LCON NAME: Mohit Chawla\r\n"
				+ "PRIMARY LCON PHONE: 3149717000\r\n"
				+ "Premise Access Hours:\r\n"
				+ "Mon     :     08:00  TO  17:00\r\n"
				+ "Tue     :     08:00  TO  17:00\r\n"
				+ "Wed     :     08:00  TO  17:00\r\n"
				+ "Thu     :     08:00  TO  17:00\r\n"
				+ "Fri     :     08:00  TO  17:00\r\n"
				+ "Sat     :     Closed  TO  Closed\r\n"
				+ "Sun     :     Closed  TO  Closed\r\n"
				+ "============================================\r\n"
				+ "======   Test/Dispatch/LCON Template   =====\r\n"
				+ "============================================\r\n"
				+ "</ns2:Log>\r\n"
				+ "                <ns3:InternalLog xmlns:ns3=\"http://tktsvc.aots.att.com/ticket\"></ns3:InternalLog>\r\n"
				+ "                <ns4:LogUserID xmlns:ns4=\"http://tktsvc.aots.att.com/ticket\">ETT</ns4:LogUserID>\r\n"
				+ "                <ns5:LogUserName xmlns:ns5=\"http://tktsvc.aots.att.com/ticket\">Express Ticketing</ns5:LogUserName>\r\n"
				+ "                <ns6:SecondaryActivityTypeCode xmlns:ns6=\"http://tktsvc.aots.att.com/ticket\">99</ns6:SecondaryActivityTypeCode>\r\n"
				+ "                <ns7:ReferralAction xmlns:ns7=\"http://tktsvc.aots.att.com/ticket\">CustomerMessage</ns7:ReferralAction>\r\n"
				+ "                <ns8:TicketSpecialNotice xmlns:ns8=\"http://tktsvc.aots.att.com/ticket\">This is an online ticket created by the Customer in Express Ticketing</ns8:TicketSpecialNotice>\r\n"
				+ "                <ns9:UserID xmlns:ns9=\"http://tktsvc.aots.att.com/ticket\">ETT</ns9:UserID>\r\n"
				+ "            </ns0:updateTicketInput>\r\n"
				+ "            <ns0:updateControlInput>\r\n"
				+ "                <ns10:FunctionalArea xmlns:ns10=\"http://tktsvc.aots.att.com/ticket\">GLOBAL_AM</ns10:FunctionalArea>\r\n"
				+ "                <ns11:TicketNum xmlns:ns11=\"http://tktsvc.aots.att.com/ticket\">"+ticketNum+"</ns11:TicketNum>\r\n"
				+ "                <ns12:LockForUpdate xmlns:ns12=\"http://tktsvc.aots.att.com/ticket\">false</ns12:LockForUpdate>\r\n"
				+ "            </ns0:updateControlInput>\r\n"
				+ "        </ns0:updateTicketRequest>\r\n"
				+ "    </soap-env:Body>\r\n"
				+ "</soap-env:Envelope>";

		
		
	}
		
		
		
	public String getRequestBody(String ticketNum) {
		return "<?xml version='1.0' encoding='utf-8'?>\r\n"
				+ "<soap-env:Envelope xmlns:soap-env=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "    <soap-env:Header>\r\n"
				+ "        <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
				+ "            <wsse:UsernameToken>\r\n"
				+ "                <wsse:Username>expresst</wsse:Username>\r\n"
				+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">etkt0813</wsse:Password>\r\n"
				+ "            </wsse:UsernameToken>\r\n"
				+ "        </wsse:Security>\r\n"
				+ "    </soap-env:Header>\r\n"
				+ "    <soap-env:Body>\r\n"
				+ "        <ns0:getTicketRequest xmlns:ns0=\"http://aots.att.com/ticket/v1\">\r\n"
				+ "            <ns1:WSHeader xmlns:ns1=\"http://cio.att.com/commonheader/v3\">\r\n"
				+ "                <ns1:WSContext>\r\n"
				+ "                    <ns1:FromAppId>ETT_aotsGetTicket</ns1:FromAppId>\r\n"
				+ "                    <ns1:SourceIPAddress>express-ticketing-84d5594bc7-wvckz</ns1:SourceIPAddress>\r\n"
				+ "                </ns1:WSContext>\r\n"
				+ "            </ns1:WSHeader>\r\n"
				+ "            <ns0:getTicketInput>\r\n"
				+ "                <ns2:FieldsList xmlns:ns2=\"http://tktsvc.aots.att.com/ticket\">\r\n"
				+ "                    <ns2:String>NBIPVPNIndicator</ns2:String>\r\n"
				+ "                    <ns2:String>ReptSvcLineDescText</ns2:String>\r\n"
				+ "                    <ns2:String>FunctionalArea</ns2:String>\r\n"
				+ "                    <ns2:String>TicketOpened</ns2:String>\r\n"
				+ "                    <ns2:String>TicketState</ns2:String>\r\n"
				+ "                    <ns2:String>TicketRole</ns2:String>\r\n"
				+ "                    <ns2:String>LocationStateProvince</ns2:String>\r\n"
				+ "                    <ns2:String>AssetLocationState</ns2:String>\r\n"
				+ "                    <ns2:String>BvoipStateProvince</ns2:String>\r\n"
				+ "                    <ns2:String>AssetLocationCountry</ns2:String>\r\n"
				+ "                    <ns2:String>BvoipCountryCode</ns2:String>\r\n"
				+ "                    <ns2:String>ISOCountryCode</ns2:String>\r\n"
				+ "                    <ns2:String>LocationCountry</ns2:String>\r\n"
				+ "                    <ns2:String>TelephoneCountryCode</ns2:String>\r\n"
				+ "                    <ns2:String>ProviderTicketNum</ns2:String>\r\n"
				+ "                    <ns2:String>ResolutionSetDescription</ns2:String>\r\n"
				+ "                    <ns2:String>CurrentStatus</ns2:String>\r\n"
				+ "                    <ns2:String>OrgGroup</ns2:String>\r\n"
				+ "                    <ns2:String>MCN</ns2:String>\r\n"
				+ "                    <ns2:String>AssetType</ns2:String>\r\n"
				+ "                    <ns2:String>ActiveOrg</ns2:String>\r\n"
				+ "                    <ns2:String>ClientTicketNum</ns2:String>\r\n"
				+ "                    <ns2:String>TestSummary</ns2:String>\r\n"
				+ "                    <ns2:String>DispatchAuthorized</ns2:String>\r\n"
				+ "                    <ns2:String>AuthTest</ns2:String>\r\n"
				+ "                </ns2:FieldsList>\r\n"
				+ "                <ns3:TicketNum xmlns:ns3=\"http://tktsvc.aots.att.com/ticket\">"+ticketNum+"</ns3:TicketNum>\r\n"
				+ "                <ns4:TicketClass xmlns:ns4=\"http://tktsvc.aots.att.com/ticket\">TT</ns4:TicketClass>\r\n"
				+ "                <ns5:LogQualifier xmlns:ns5=\"http://tktsvc.aots.att.com/ticket\">3</ns5:LogQualifier>\r\n"
				+ "                <ns6:GetLocationInfo xmlns:ns6=\"http://tktsvc.aots.att.com/ticket\">true</ns6:GetLocationInfo>\r\n"
				+ "                <ns7:GetPVCDetailsInfo xmlns:ns7=\"http://tktsvc.aots.att.com/ticket\">true</ns7:GetPVCDetailsInfo>\r\n"
				+ "                <ns8:GetLocationDetailsInfo xmlns:ns8=\"http://tktsvc.aots.att.com/ticket\">true</ns8:GetLocationDetailsInfo>\r\n"
				+ "                <ns9:GetEventTotalDowntimeInfo xmlns:ns9=\"http://tktsvc.aots.att.com/ticket\">true</ns9:GetEventTotalDowntimeInfo>\r\n"
				+ "                <ns10:GetBvoipLocationInfo xmlns:ns10=\"http://tktsvc.aots.att.com/ticket\">true</ns10:GetBvoipLocationInfo>\r\n"
				+ "                <ns11:GetMTTRInfo xmlns:ns11=\"http://tktsvc.aots.att.com/ticket\">true</ns11:GetMTTRInfo>\r\n"
				+ "                <ns12:GetMTTRChangeHistoryInfo xmlns:ns12=\"http://tktsvc.aots.att.com/ticket\">true</ns12:GetMTTRChangeHistoryInfo>\r\n"
				+ "                <ns13:GetTestResultsInfo xmlns:ns13=\"http://tktsvc.aots.att.com/ticket\">true</ns13:GetTestResultsInfo>\r\n"
				+ "                <ns14:GetAccountContractDetailsInfo xmlns:ns14=\"http://tktsvc.aots.att.com/ticket\">true</ns14:GetAccountContractDetailsInfo>\r\n"
				+ "                <ns15:GetUniqueLogID xmlns:ns15=\"http://tktsvc.aots.att.com/ticket\">true</ns15:GetUniqueLogID>\r\n"
				+ "                <ns16:GetIVRNotificationEventsInfo xmlns:ns16=\"http://tktsvc.aots.att.com/ticket\">true</ns16:GetIVRNotificationEventsInfo>\r\n"
				+ "                <ns17:GetLCONDetailsInfo xmlns:ns17=\"http://tktsvc.aots.att.com/ticket\">true</ns17:GetLCONDetailsInfo>\r\n"
				+ "                <ns18:GetRelatedTicketInfo xmlns:ns18=\"http://tktsvc.aots.att.com/ticket\">true</ns18:GetRelatedTicketInfo>\r\n"
				+ "            </ns0:getTicketInput>\r\n"
				+ "        </ns0:getTicketRequest>\r\n"
				+ "    </soap-env:Body>\r\n"
				+ "</soap-env:Envelope>";
		
	
	}
	
	public String closeRequestBody(String ticketNum) {
		return "<?xml version='1.0' encoding='utf-8'?>\r\n"
				+ "<soap-env:Envelope xmlns:soap-env=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "    <soap-env:Header>\r\n"
				+ "        <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
				+ "            <wsse:UsernameToken>\r\n"
				+ "                <wsse:Username>expresst</wsse:Username>\r\n"
				+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">etkt0813</wsse:Password>\r\n"
				+ "            </wsse:UsernameToken>\r\n"
				+ "        </wsse:Security>\r\n"
				+ "    </soap-env:Header>\r\n"
				+ "    <soap-env:Body>\r\n"
				+ "        <ns0:updateTicketRequest xmlns:ns0=\"http://aots.att.com/ticket/v1\">\r\n"
				+ "            <ns1:WSHeader xmlns:ns1=\"http://cio.att.com/commonheader/v3\">\r\n"
				+ "                <ns1:WSContext>\r\n"
				+ "                    <ns1:FromAppId>ETT_aotsRequestToClose</ns1:FromAppId>\r\n"
				+ "                    <ns1:SourceIPAddress>express-ticketing-84d5594bc7-wvckz</ns1:SourceIPAddress>\r\n"
				+ "                </ns1:WSContext>\r\n"
				+ "            </ns1:WSHeader>\r\n"
				+ "            <ns0:updateTicketInput>\r\n"
				+ "                <ns2:Log xmlns:ns2=\"http://tktsvc.aots.att.com/ticket\">CUSTOMER TICKET CLOSURE REQUEST \\nEXPRESS TICKETING CUSTOMER STATES: \r\n"
				+ "Contact Name: Mohit Chawla\r\n"
				+ "Contact Phone: (314) 971-7200\r\n"
				+ "Contact Email Address: mc9844@att.com\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Closing ticket - session2 - 09282021</ns2:Log>\r\n"
				+ "                <ns3:LogUserID xmlns:ns3=\"http://tktsvc.aots.att.com/ticket\">ETT</ns3:LogUserID>\r\n"
				+ "                <ns4:LogUserName xmlns:ns4=\"http://tktsvc.aots.att.com/ticket\">Express Ticketing</ns4:LogUserName>\r\n"
				+ "                <ns5:LogUserPhone xmlns:ns5=\"http://tktsvc.aots.att.com/ticket\"></ns5:LogUserPhone>\r\n"
				+ "                <ns6:SecondaryActivityTypeCode xmlns:ns6=\"http://tktsvc.aots.att.com/ticket\">99</ns6:SecondaryActivityTypeCode>\r\n"
				+ "                <ns7:NextCheckTime xmlns:ns7=\"http://tktsvc.aots.att.com/ticket\">1631125067</ns7:NextCheckTime>\r\n"
				+ "                <ns8:ReferralAction xmlns:ns8=\"http://tktsvc.aots.att.com/ticket\">RequestToClose</ns8:ReferralAction>\r\n"
				+ "                <ns9:UserID xmlns:ns9=\"http://tktsvc.aots.att.com/ticket\">ETT</ns9:UserID>\r\n"
				+ "                <ns10:RFTicketNumList xmlns:ns10=\"http://tktsvc.aots.att.com/ticket\"></ns10:RFTicketNumList>\r\n"
				+ "            </ns0:updateTicketInput>\r\n"
				+ "            <ns0:updateControlInput>\r\n"
				+ "                <ns11:FunctionalArea xmlns:ns11=\"http://tktsvc.aots.att.com/ticket\">GLOBAL_AM</ns11:FunctionalArea>\r\n"
				+ "                <ns12:TicketNum xmlns:ns12=\"http://tktsvc.aots.att.com/ticket\">"+ticketNum+"</ns12:TicketNum>\r\n"
				+ "                <ns13:LockForUpdate xmlns:ns13=\"http://tktsvc.aots.att.com/ticket\">false</ns13:LockForUpdate>\r\n"
				+ "            </ns0:updateControlInput>\r\n"
				+ "        </ns0:updateTicketRequest>\r\n"
				+ "    </soap-env:Body>\r\n"
				+ "</soap-env:Envelope>";

}
	
	
	public String telePhoneNumRequestBody(String phoneNumber) {
		return "{\r\n"
				+ "    \"short_description\": \"Test Ticket creation\",\r\n"
				+ "    \"contact_type\": \"web\",\r\n"
				+ "    \"is_test_authorized\": \"no\",\r\n"
				+ "    \"power_to_cpe\": \"yes\",\r\n"
				+ "    \"is_dispatch_authorized\": \"no\",\r\n"
				+ "    \"contact\": \"nj5695@exo.att.com\",\r\n"
				+ "    \"priority\": \"4\",\r\n"
				+ "    \"category\": \"Informational\",\r\n"
				+ "    \"contactfirstname\": \"NEENA\",\r\n"
				+ "    \"contactlastname\": \"JETHANI\",\r\n"
				+ "    \"contact_phone\": \"7324200703\",\r\n"
				+ "    \"reported_trouble\": \"Informational\",\r\n"
				+ "    \"primary_site_contact_name\": \"Mohit Chawla\",\r\n"
				+ "    \"primary_site_contact_phone\": \"9082348256\",\r\n"
				+ "    \"primary_site_contact_email\": \"fsinkovits@att.com\",\r\n"
				+ "    \"site_access_hours\": \"{\\\"listofaccesshour\\\":[{\\\"day_of_week\\\":\\\"MON\\\",\\\"start\\\":\\\"08:00\\\",\\\"end\\\":\\\"17:00\\\"},{\\\"day_of_week\\\":\\\"TUE\\\",\\\"start\\\":\\\"08:00\\\",\\\"end\\\":\\\"17:00\\\"},{\\\"day_of_week\\\":\\\"WED\\\",\\\"start\\\":\\\"08:00\\\",\\\"end\\\":\\\"17:00\\\"},{\\\"day_of_week\\\":\\\"THU\\\",\\\"start\\\":\\\"08:00\\\",\\\"end\\\":\\\"17:00\\\"},{\\\"day_of_week\\\":\\\"FRI\\\",\\\"start\\\":\\\"08:00\\\",\\\"end\\\":\\\"17:00\\\"},{\\\"day_of_week\\\":\\\"SAT\\\",\\\"start\\\":\\\"08:00\\\",\\\"end\\\":\\\"17:00\\\"},{\\\"day_of_week\\\":\\\"SUN\\\",\\\"start\\\":\\\"08:00\\\",\\\"end\\\":\\\"17:00\\\"}]}\",\r\n"
				+ "    \"reported_item\": \"+"+phoneNumber+"\",\r\n"
				+ "    \"reported_type\": \"Telephone Number\",\r\n"
				+ "    \"callingsystem\": \"NOWIA\"\r\n"
				+ "}";
		
	}
	
	public String logUpdateRequestBody(String caseNumber,String phoneNumber) {
		return"{\r\n"
				+ "    \"comments\": \"Adding new notes from EM to ATTNOW\",\r\n"
				+ "    \"contact\": \"nj5695@exo.att.com\",\r\n"
				+ "    \"priority\": \"4\",\r\n"
				+ "    \"case_number\": \""+caseNumber+"\",\r\n"
				+ "    \"contactfirstname\": \"NEENA\",\r\n"
				+ "    \"contactlastname\": \"JETHANI\",\r\n"
				+ "    \"contact_phone\": \""+phoneNumber+"\",\r\n"
				+ "    \"follow_up\": \"2021-11-29 15:57:12\",\r\n"
				+ "    \"callingsystem\": \"NOWIA\"\r\n"
				+ "}";
	}
	
	
	public String caseEscalationRequestBody(String caseNumber,String phoneNumber) {
		return"{\r\n"
				+ "  \"comments\" : \"*****Customer Requests Escalation of Ticket *****\\nEscalation Level: 1\\nEscalation DeadLine: Monday, 29 Nov 2021 16:32:08 UTC\\nEscalating a case from EM\",\r\n"
				+ "  \"contact\" : \"nj5695@exo.att.com\",\r\n"
				+ "  \"priority\" : \"4\",\r\n"
				+ "  \"case_number\" : \""+caseNumber+"\",\r\n"
				+ "  \"contactfirstname\" : \"NEENA\",\r\n"
				+ "  \"contactlastname\" : \"JETHANI\",\r\n"
				+ "  \"contact_phone\" : \""+phoneNumber+"\",\r\n"
				+ "  \"follow_up\" : \"2021-11-29 15:32:08\",\r\n"
				+ "  \"callingsystem\" : \"NOWIA\"\r\n"
				+ "}";
	}
	

	public String caseClosureRequestBody(String caseNumber,String phoneNumber) {
		return"{\r\n"
				+ "    \"comments\": \"\\\"Important : The Customer requested to close this ticket. Please review whether there is an associated ticket or not. If not, close this ticket.\\\"Closing the case from EM - 11292021\",\r\n"
				+ "    \"contact\": \"nj5695@exo.att.com\",\r\n"
				+ "    \"priority\": \"4\",\r\n"
				+ "    \"case_number\": \""+caseNumber+"\",\r\n"
				+ "    \"contactfirstname\": \"NEENA\",\r\n"
				+ "    \"contactlastname\": \"JETHANI\",\r\n"
				+ "    \"contact_phone\": \""+phoneNumber+"\",\r\n"
				+ "    \"follow_up\": \"2021-11-29 16:08:39\",\r\n"
				+ "    \"callingsystem\": \"NOWIA\"\r\n"
				+ "}";
	}
	
	
	
}


