package constants;

public class RequestPayLoad {
	
	
	
public String createRequestBody(String ticketNum) {
		
		return "<soap:Envelope xmlns:soap=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "    <soap:Header>\r\n"
				+ "        <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
				+ "            <wsse:UsernameToken wsu=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\">\r\n"
				+ "                <wsse:Username>em</wsse:Username>\r\n"
				+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">em=123</wsse:Password>\r\n"
				+ "            </wsse:UsernameToken>\r\n"
				+ "        </wsse:Security>\r\n"
				+ "    </soap:Header>\r\n"
				+ "    <soap:Body>\r\n"
				+ "        <ns3:createTicketRequest xmlns=\"http://cio.att.com/commonheader/v3\" xmlns:ns2=\"http://tktsvc.aots.att.com/ticket\" xmlns:ns3=\"http://aots.att.com/ticket/v1\" xmlns:ns4=\"http://cio.att.com/CommonHeader/v1\">\r\n"
				+ "            <WSHeader>\r\n"
				+ "                <WSContext>\r\n"
				+ "                    <FromAppId>EM</FromAppId>\r\n"
				+ "                    <SourceIPAddress>aotsyjl.test.att.com</SourceIPAddress>\r\n"
				+ "                </WSContext>\r\n"
				+ "            </WSHeader>\r\n"
				+ "            <ns3:createTicketInput>\r\n"
				+ "                <ns2:RemoteAgentID>testsk7773</ns2:RemoteAgentID>\r\n"
				+ "                <ns2:ClientTicketNum></ns2:ClientTicketNum>\r\n"
				+ "                <ns2:FunctionalArea>GLOBAL_AM</ns2:FunctionalArea>\r\n"
				+ "                <ns2:Log>\r\n"
				+ "IP From: \r\n"
				+ "IP To: \r\n"
				+ "</ns2:Log>\r\n"
				+ "                <ns2:ProblemAbstract>Test Create RTR from EM</ns2:ProblemAbstract>\r\n"
				+ "                <ns2:ReptRequestType>Informational</ns2:ReptRequestType>\r\n"
				+ "                <ns2:ReptSvcImpactFlag>No</ns2:ReptSvcImpactFlag>\r\n"
				+ "                <ns2:Severity>5 - Normal</ns2:Severity>\r\n"
				+ "                <ns2:TicketType>WEB</ns2:TicketType>\r\n"
				+ "                <ns2:ReportedBy>NEENA JETHANI</ns2:ReportedBy>\r\n"
				+ "                <ns2:ReportPhone>7324200703</ns2:ReportPhone>\r\n"
				+ "                <ns2:TicketSource>EM</ns2:TicketSource>\r\n"
				+ "                <ns2:TroubleReptDescText>Informational</ns2:TroubleReptDescText>\r\n"
				+ "                <ns2:ReporterEmailAddr>nj5695@exo.att.com</ns2:ReporterEmailAddr>\r\n"
				+ "                <ns2:AccountContactName>Laxmi</ns2:AccountContactName>\r\n"
				+ "                <ns2:AccountPhone>6158800935</ns2:AccountPhone>\r\n"
				+ "                <ns2:CustomerChronic>No</ns2:CustomerChronic>\r\n"
				+ "                <ns2:LogUserID>testsk7773</ns2:LogUserID>\r\n"
				+ "                <ns2:LogUserName>NEENA JETHANI</ns2:LogUserName>\r\n"
				+ "                <ns2:LogUserPhone>7324200703</ns2:LogUserPhone>\r\n"
				+ "                <ns2:PowerToCPE>Y</ns2:PowerToCPE>\r\n"
				+ "                <ns2:TroubleReptCode>39</ns2:TroubleReptCode>\r\n"
				+ "                <ns2:AccountContactEmail>hl096f@att.com</ns2:AccountContactEmail>\r\n"
				+ "                <ns2:CompanyID>5mbbtcan</ns2:CompanyID>\r\n"
				+ "                <ns2:ReporterEmailNotifyFlag>No</ns2:ReporterEmailNotifyFlag>\r\n"
				+ "                <ns2:DispatchAuthorized>N</ns2:DispatchAuthorized>\r\n"
				+ "                <ns2:SeverityClassification></ns2:SeverityClassification>\r\n"
				+ "                <ns2:ContractType></ns2:ContractType>\r\n"
				+ "                <ns2:UserID>EM_SAPrimary_Name_Phone_Email update ,EM_LCON_Name update </ns2:UserID>\r\n"
				+ "                <ns2:ValidateContactInfo>Yes</ns2:ValidateContactInfo>\r\n"
				+ "                <ns2:ValidateDispatchAuth>Yes</ns2:ValidateDispatchAuth>\r\n"
				+ "                <ns2:ValidateLCONInfo>Yes</ns2:ValidateLCONInfo>\r\n"
				+ "                <ns2:ValidateLocationAccessHours>Yes</ns2:ValidateLocationAccessHours>\r\n"
				+ "                <ns2:ValidatePowerToCPE>Yes</ns2:ValidatePowerToCPE>\r\n"
				+ "                <ns2:ValidateTestAuth>Yes</ns2:ValidateTestAuth>\r\n"
				+ "                <ns2:ValidationResponsesRcvd>Yes</ns2:ValidationResponsesRcvd>\r\n"
				+ "            </ns3:createTicketInput>\r\n"
				+ "            <ns3:assetInput>\r\n"
				+ "                <ns2:AssetID>USORT3MTNNJO5R</ns2:AssetID>\r\n"
				+ "                <ns2:ClientName>BVOIP Company D_Test</ns2:ClientName>\r\n"
				+ "                <ns2:CircuitID>USORT3MTNNJO5R</ns2:CircuitID>\r\n"
				+ "                <ns2:CountryCode>USA</ns2:CountryCode>\r\n"
				+ "                <ns2:CallbackContact>Laxmi H Pluemacher</ns2:CallbackContact>\r\n"
				+ "                <ns2:CallbackPhone></ns2:CallbackPhone>\r\n"
				+ "                <ns2:BvoipIndicator>Yes</ns2:BvoipIndicator>\r\n"
				+ "                <ns2:BvoipCity>MIDDLETOWN</ns2:BvoipCity>\r\n"
				+ "                <ns2:BvoipStateProvince>NJ</ns2:BvoipStateProvince>\r\n"
				+ "                <ns2:BvoipZipPostal>07748</ns2:BvoipZipPostal>\r\n"
				+ "                <ns2:BvoipCountryCode>USA</ns2:BvoipCountryCode>\r\n"
				+ "                <ns2:AgencyID></ns2:AgencyID>\r\n"
				+ "                <ns2:AgencyName>BVOIP Company D_Test</ns2:AgencyName>\r\n"
				+ "                <ns2:LocationDetailsInfoList>\r\n"
				+ "                    <ns2:LocationDetailsInfo>\r\n"
				+ "                        <ns2:LocationContactName>Laxmi H Pluemacher</ns2:LocationContactName>\r\n"
				+ "                        <ns2:LocationContactPhone>7324208433</ns2:LocationContactPhone>\r\n"
				+ "                        <ns2:LocationContactEmail>cpluemacher@att.com</ns2:LocationContactEmail>\r\n"
				+ "                        <ns2:PremiseAccessHoursInfoList>\r\n"
				+ "                            <ns2:AccessHoursInfo>\r\n"
				+ "                                <ns2:DayOfWeek>MON</ns2:DayOfWeek>\r\n"
				+ "                                <ns2:Start>08:00</ns2:Start>\r\n"
				+ "                                <ns2:End>17:00</ns2:End>\r\n"
				+ "                            </ns2:AccessHoursInfo>\r\n"
				+ "                            <ns2:AccessHoursInfo>\r\n"
				+ "                                <ns2:DayOfWeek>TUE</ns2:DayOfWeek>\r\n"
				+ "                                <ns2:Start>08:00</ns2:Start>\r\n"
				+ "                                <ns2:End>17:00</ns2:End>\r\n"
				+ "                            </ns2:AccessHoursInfo>\r\n"
				+ "                            <ns2:AccessHoursInfo>\r\n"
				+ "                                <ns2:DayOfWeek>WED</ns2:DayOfWeek>\r\n"
				+ "                                <ns2:Start>08:00</ns2:Start>\r\n"
				+ "                                <ns2:End>17:00</ns2:End>\r\n"
				+ "                            </ns2:AccessHoursInfo>\r\n"
				+ "                            <ns2:AccessHoursInfo>\r\n"
				+ "                                <ns2:DayOfWeek>THU</ns2:DayOfWeek>\r\n"
				+ "                                <ns2:Start>08:00</ns2:Start>\r\n"
				+ "                                <ns2:End>17:00</ns2:End>\r\n"
				+ "                            </ns2:AccessHoursInfo>\r\n"
				+ "                            <ns2:AccessHoursInfo>\r\n"
				+ "                                <ns2:DayOfWeek>FRI</ns2:DayOfWeek>\r\n"
				+ "                                <ns2:Start>08:00</ns2:Start>\r\n"
				+ "                                <ns2:End>17:00</ns2:End>\r\n"
				+ "                            </ns2:AccessHoursInfo>\r\n"
				+ "                            <ns2:AccessHoursInfo>\r\n"
				+ "                                <ns2:DayOfWeek>SAT</ns2:DayOfWeek>\r\n"
				+ "                                <ns2:Start>08:00</ns2:Start>\r\n"
				+ "                                <ns2:End>17:00</ns2:End>\r\n"
				+ "                            </ns2:AccessHoursInfo>\r\n"
				+ "                            <ns2:AccessHoursInfo>\r\n"
				+ "                                <ns2:DayOfWeek>SUN</ns2:DayOfWeek>\r\n"
				+ "                                <ns2:Start>08:00</ns2:Start>\r\n"
				+ "                                <ns2:End>17:00</ns2:End>\r\n"
				+ "                            </ns2:AccessHoursInfo>\r\n"
				+ "                        </ns2:PremiseAccessHoursInfoList>\r\n"
				+ "                        <ns2:LocationDetailsType>L</ns2:LocationDetailsType>\r\n"
				+ "                    </ns2:LocationDetailsInfo>\r\n"
				+ "                </ns2:LocationDetailsInfoList>\r\n"
				+ "                <ns2:BvoipProbeIndicator>N</ns2:BvoipProbeIndicator>\r\n"
				+ "                <ns2:GDBAssetObjectID>84775047</ns2:GDBAssetObjectID>\r\n"
				+ "                <ns2:GDBContactObjectID>0</ns2:GDBContactObjectID>\r\n"
				+ "                <ns2:GDBOrgObjectID>0</ns2:GDBOrgObjectID>\r\n"
				+ "                <ns2:ResellerIndicator>N</ns2:ResellerIndicator>\r\n"
				+ "            </ns3:assetInput>\r\n"
				+ "            <ns3:createControlInput>\r\n"
				+ "                <ns2:AssetLookupType>BVOIP_RTR</ns2:AssetLookupType>\r\n"
				+ "                <ns2:CreateType>U</ns2:CreateType>\r\n"
				+ "                <ns2:RetrieveAssetInfo>R</ns2:RetrieveAssetInfo>\r\n"
				+ "            </ns3:createControlInput>\r\n"
				+ "        </ns3:createTicketRequest>\r\n"
				+ "    </soap:Body>\r\n"
				+ "</soap:Envelope>";

		
		
	}
		
		
		
	public String getRequestBody(String ticketNum) {
		return "	<?xml version='1.0' encoding='utf-8'?>\r\n"
				+ "		<soap-env:Envelope xmlns:soap-env=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "		    <soap-env:Header>\r\n"
				+ "		        <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
				+ "		            <wsse:UsernameToken>\r\n"
				+ "		                <wsse:Username>expresst</wsse:Username>\r\n"
				+ "		                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">etkt0813</wsse:Password>\r\n"
				+ "		            </wsse:UsernameToken>\r\n"
				+ "		        </wsse:Security>\r\n"
				+ "		    </soap-env:Header>\r\n"
				+ "		    <soap-env:Body>\r\n"
				+ "		        <ns0:getTicketRequest xmlns:ns0=\"http://aots.att.com/ticket/v1\">\r\n"
				+ "		            <ns1:WSHeader xmlns:ns1=\"http://cio.att.com/commonheader/v3\">\r\n"
				+ "		                <ns1:WSContext>\r\n"
				+ "		                    <ns1:FromAppId>ETT_aotsGetTicket</ns1:FromAppId>\r\n"
				+ "		                    <ns1:SourceIPAddress>express-ticketing-84d5594bc7-wvckz</ns1:SourceIPAddress>\r\n"
				+ "		                </ns1:WSContext>\r\n"
				+ "		            </ns1:WSHeader>\r\n"
				+ "		            <ns0:getTicketInput>\r\n"
				+ "		                <ns2:FieldsList xmlns:ns2=\"http://tktsvc.aots.att.com/ticket\">\r\n"
				+ "		                    <ns2:String>NBIPVPNIndicator</ns2:String>\r\n"
				+ "		                    <ns2:String>ReptSvcLineDescText</ns2:String>\r\n"
				+ "		                    <ns2:String>FunctionalArea</ns2:String>\r\n"
				+ "		                    <ns2:String>TicketOpened</ns2:String>\r\n"
				+ "		                    <ns2:String>TicketState</ns2:String>\r\n"
				+ "		                    <ns2:String>TicketRole</ns2:String>\r\n"
				+ "		                    <ns2:String>LocationStateProvince</ns2:String>\r\n"
				+ "		                    <ns2:String>AssetLocationState</ns2:String>\r\n"
				+ "		                    <ns2:String>BvoipStateProvince</ns2:String>\r\n"
				+ "		                    <ns2:String>AssetLocationCountry</ns2:String>\r\n"
				+ "		                    <ns2:String>BvoipCountryCode</ns2:String>\r\n"
				+ "		                    <ns2:String>ISOCountryCode</ns2:String>\r\n"
				+ "		                    <ns2:String>LocationCountry</ns2:String>\r\n"
				+ "		                    <ns2:String>TelephoneCountryCode</ns2:String>\r\n"
				+ "		                    <ns2:String>ProviderTicketNum</ns2:String>\r\n"
				+ "		                    <ns2:String>ResolutionSetDescription</ns2:String>\r\n"
				+ "		                    <ns2:String>CurrentStatus</ns2:String>\r\n"
				+ "		                    <ns2:String>OrgGroup</ns2:String>\r\n"
				+ "		                    <ns2:String>MCN</ns2:String>\r\n"
				+ "		                    <ns2:String>AssetType</ns2:String>\r\n"
				+ "		                    <ns2:String>ActiveOrg</ns2:String>\r\n"
				+ "		                    <ns2:String>ClientTicketNum</ns2:String>\r\n"
				+ "		                    <ns2:String>TestSummary</ns2:String>\r\n"
				+ "		                    <ns2:String>DispatchAuthorized</ns2:String>\r\n"
				+ "		                    <ns2:String>AuthTest</ns2:String>\r\n"
				+ "		                </ns2:FieldsList>\r\n"
				+ "		                <ns3:TicketNum xmlns:ns3=\"http://tktsvc.aots.att.com/ticket\">"+ticketNum+"</ns3:TicketNum>\r\n"
				+ "		                <ns4:TicketClass xmlns:ns4=\"http://tktsvc.aots.att.com/ticket\">TT</ns4:TicketClass>\r\n"
				+ "		                <ns5:LogQualifier xmlns:ns5=\"http://tktsvc.aots.att.com/ticket\">3</ns5:LogQualifier>\r\n"
				+ "		                <ns6:GetLocationInfo xmlns:ns6=\"http://tktsvc.aots.att.com/ticket\">true</ns6:GetLocationInfo>\r\n"
				+ "		                <ns7:GetPVCDetailsInfo xmlns:ns7=\"http://tktsvc.aots.att.com/ticket\">true</ns7:GetPVCDetailsInfo>\r\n"
				+ "		                <ns8:GetLocationDetailsInfo xmlns:ns8=\"http://tktsvc.aots.att.com/ticket\">true</ns8:GetLocationDetailsInfo>\r\n"
				+ "		                <ns9:GetEventTotalDowntimeInfo xmlns:ns9=\"http://tktsvc.aots.att.com/ticket\">true</ns9:GetEventTotalDowntimeInfo>\r\n"
				+ "		                <ns10:GetBvoipLocationInfo xmlns:ns10=\"http://tktsvc.aots.att.com/ticket\">true</ns10:GetBvoipLocationInfo>\r\n"
				+ "		                <ns11:GetMTTRInfo xmlns:ns11=\"http://tktsvc.aots.att.com/ticket\">true</ns11:GetMTTRInfo>\r\n"
				+ "		                <ns12:GetMTTRChangeHistoryInfo xmlns:ns12=\"http://tktsvc.aots.att.com/ticket\">true</ns12:GetMTTRChangeHistoryInfo>\r\n"
				+ "		                <ns13:GetTestResultsInfo xmlns:ns13=\"http://tktsvc.aots.att.com/ticket\">true</ns13:GetTestResultsInfo>\r\n"
				+ "		                <ns14:GetAccountContractDetailsInfo xmlns:ns14=\"http://tktsvc.aots.att.com/ticket\">true</ns14:GetAccountContractDetailsInfo>\r\n"
				+ "		                <ns15:GetUniqueLogID xmlns:ns15=\"http://tktsvc.aots.att.com/ticket\">true</ns15:GetUniqueLogID>\r\n"
				+ "		                <ns16:GetIVRNotificationEventsInfo xmlns:ns16=\"http://tktsvc.aots.att.com/ticket\">true</ns16:GetIVRNotificationEventsInfo>\r\n"
				+ "		                <ns17:GetLCONDetailsInfo xmlns:ns17=\"http://tktsvc.aots.att.com/ticket\">true</ns17:GetLCONDetailsInfo>\r\n"
				+ "		                <ns18:GetRelatedTicketInfo xmlns:ns18=\"http://tktsvc.aots.att.com/ticket\">true</ns18:GetRelatedTicketInfo>\r\n"
				+ "		            </ns0:getTicketInput>\r\n"
				+ "		        </ns0:getTicketRequest>\r\n"
				+ "		    </soap-env:Body>\r\n"
				+ "		</soap-env:Envelope>";
		
	
	}
	
/*	public String closeRequestBody(String ticketNum) {
		return "<?xml version='1.0' encoding='utf-8'?>\r\n"
				+ "<soap-env:Envelope xmlns:soap-env=\"http://schemas.xmlsoap.org/soap/envelope/\">\r\n"
				+ "    <soap-env:Header>\r\n"
				+ "        <wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
				+ "            <wsse:UsernameToken>\r\n"
				+ "                <wsse:Username>expresst</wsse:Username>\r\n"
				+ "                <wsse:Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordText\">etkt0813</wsse:Password>\r\n"
				+ "            </wsse:UsernameToken>\r\n"
				+ "        </wsse:Security>\r\n"
				+ "    </soap-env:Header>\r\n"
				+ "    <soap-env:Body>\r\n"
				+ "        <ns0:updateTicketRequest xmlns:ns0=\"http://aots.att.com/ticket/v1\">\r\n"
				+ "            <ns1:WSHeader xmlns:ns1=\"http://cio.att.com/commonheader/v3\">\r\n"
				+ "                <ns1:WSContext>\r\n"
				+ "                    <ns1:FromAppId>ETT_aotsRequestToClose</ns1:FromAppId>\r\n"
				+ "                    <ns1:SourceIPAddress>express-ticketing-84d5594bc7-wvckz</ns1:SourceIPAddress>\r\n"
				+ "                </ns1:WSContext>\r\n"
				+ "            </ns1:WSHeader>\r\n"
				+ "            <ns0:updateTicketInput>\r\n"
				+ "                <ns2:Log xmlns:ns2=\"http://tktsvc.aots.att.com/ticket\">CUSTOMER TICKET CLOSURE REQUEST \\nEXPRESS TICKETING CUSTOMER STATES: \r\n"
				+ "Contact Name: Mohit Chawla\r\n"
				+ "Contact Phone: (314) 971-7200\r\n"
				+ "Contact Email Address: mc9844@att.com\r\n"
				+ "\r\n"
				+ "\r\n"
				+ "Closing ticket - session2 - 09282021</ns2:Log>\r\n"
				+ "                <ns3:LogUserID xmlns:ns3=\"http://tktsvc.aots.att.com/ticket\">ETT</ns3:LogUserID>\r\n"
				+ "                <ns4:LogUserName xmlns:ns4=\"http://tktsvc.aots.att.com/ticket\">Express Ticketing</ns4:LogUserName>\r\n"
				+ "                <ns5:LogUserPhone xmlns:ns5=\"http://tktsvc.aots.att.com/ticket\"></ns5:LogUserPhone>\r\n"
				+ "                <ns6:SecondaryActivityTypeCode xmlns:ns6=\"http://tktsvc.aots.att.com/ticket\">99</ns6:SecondaryActivityTypeCode>\r\n"
				+ "                <ns7:NextCheckTime xmlns:ns7=\"http://tktsvc.aots.att.com/ticket\">1631125067</ns7:NextCheckTime>\r\n"
				+ "                <ns8:ReferralAction xmlns:ns8=\"http://tktsvc.aots.att.com/ticket\">RequestToClose</ns8:ReferralAction>\r\n"
				+ "                <ns9:UserID xmlns:ns9=\"http://tktsvc.aots.att.com/ticket\">ETT</ns9:UserID>\r\n"
				+ "                <ns10:RFTicketNumList xmlns:ns10=\"http://tktsvc.aots.att.com/ticket\"></ns10:RFTicketNumList>\r\n"
				+ "            </ns0:updateTicketInput>\r\n"
				+ "            <ns0:updateControlInput>\r\n"
				+ "                <ns11:FunctionalArea xmlns:ns11=\"http://tktsvc.aots.att.com/ticket\">GLOBAL_AM</ns11:FunctionalArea>\r\n"
				+ "                <ns12:TicketNum xmlns:ns12=\"http://tktsvc.aots.att.com/ticket\">"+ticketNum+"</ns12:TicketNum>\r\n"
				+ "                <ns13:LockForUpdate xmlns:ns13=\"http://tktsvc.aots.att.com/ticket\">false</ns13:LockForUpdate>\r\n"
				+ "            </ns0:updateControlInput>\r\n"
				+ "        </ns0:updateTicketRequest>\r\n"
				+ "    </soap-env:Body>\r\n"
				+ "</soap-env:Envelope>";

}
*/


}
